export const categoryOptions = {
  endurance: ["running", "cycling", "swimming", "walking"],
  strength: [
    "pull-ups",
    "push-ups",
    "glute bridges",
    "squats",
    "deadlifts",
    "walking lunges",
    "bicep curls",
    "overhead tricep extensions",
    "boat pose",
    "planks",
  ],
  balance: [
    "single leg deadlifts",
    "speed skaters",
    "single leg squats",
    "lunge and twist",
    "single leg jump squats",
    "lunge to front kick",
    "side plank oblique crunch",
    "limb raise push-ups",
    "low plank crunches",
    "one-legged 4 count burpees",
  ],
  flexibility: [
    "dynamic lunges",
    "stair calf stretch",
    "lizard pose",
    "lying quad stretch",
    "overhead triceps stretch",
    "standing hamstring stretch",
    "cat cow",
    "sphinx pose",
    "shoulder rolls",
    "wrist figure 8's",
  ],
};
